apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: blue
  template:
    metadata:
      labels:
        app: nginx
        version: blue
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 200Mi 
        volumeMounts:
        - name: html-dir 
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-dir
        configMap:
          name: nginx-html-blue


